Repository SBNSoftware/sbncode, pull requests merged in 2021-12, with the labels that each got.

#207 BNBRetriever fix: don't write entries incrementally
  sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
Labels: bug

#206 Add another globalTree bail out condition for the case where the list of labels is empty
  sbncode/CAFMaker/CAFMaker_module.cc
Labels: maintenance

#212 SBNEventWeight_fix bugs that slow down the code & of incorrect looping.
  sbncode/SBNEventWeight/Calculators/CrossSections/GenieWeightCalc.cxx
  sbncode/SBNEventWeight/jobs/genie/eventweight_genie_sbn.fcl
Labels: bug

#208 BNBRetriever fix: fill event number
  sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
Labels: bug

#222 Greenlee pid update
  CMakeLists.txt
  sbncode/CAFMaker/FillReco.cxx
  sbncode/PID/Dazzle_module.cc
  sbncode/TPCReco/CalorimetryAnalysis/CalorimetryAnalysis_module.cc
Labels: enhancement
