Repository SBNSoftware/sbncode, pull requests merged in 2021-08, with the labels that each got.

#152 Simple-Flash Match: multi-matcher, unbiased, tuneable, fast.
  sbncode/FlashMatch/CMakeLists.txt
  sbncode/FlashMatch/FlashPredict.hh
  sbncode/FlashMatch/FlashPredict_module.cc
  sbncode/FlashMatch/template_generators/generate_simple_weighted_template.py
Labels: enhancement

#158 Add missing definition for fmatch
  sbncode/CAFMaker/cafmakerjob_sbnd_fmatch.fcl
Labels: bug

#151 Generalize CAFMaker to be able to accept multiple SystWeightLabels
  sbncode/CAFMaker/CAFMaker.fcl
  sbncode/CAFMaker/CAFMakerParams.h
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/FillTrue.cxx
  sbncode/CAFMaker/FillTrue.h
  sbncode/CAFMaker/cafmakerjob_icarus.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_3drift_sce_runfmatch_geniewgt.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_geniewgt.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_sce_geniewgt.fcl
Labels: enhancement

#161 Don't crash if weights are not present and strictmode==false
  sbncode/CAFMaker/CAFMaker_module.cc
Labels: maintenance

#163 Heuristic method for determining detector ID
  sbncode/CAFMaker/CAFMaker_module.cc
Labels: enhancement

#156 Updates to Configurations for ICARUS MCP
  fcl/CMakeLists.txt
  fcl/caf/CAFMaker.fcl
  fcl/caf/CMakeLists.txt
  fcl/caf/sbnd/CMakeLists.txt
  fcl/caf/sbnd/cafmakerjob_sbnd.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_3drift_sce.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_3drift_sce_runfmatch.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_3drift_sce_runfmatch_geniewgt.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_fmatch.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_geniewgt.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_sce.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_sce_geniewgt.fcl
  sbncode/CAFMaker/FillReco.cxx
  sbncode/CAFMaker/FillTrue.cxx
  sbncode/CAFMaker/cafmakerjob.fcl
  sbncode/CAFMaker/cafmakerjob_icarus.fcl
  sbncode/CAFMaker/cafmakerjob_icarus_fmatch.fcl
  sbncode/CAFMaker/cafmakerjob_icarus_sce.fcl
  sbncode/EventGenerator/MeVPrtl/Tools/IMeVPrtlDecay.h
  sbncode/EventGenerator/MeVPrtl/Tools/IMeVPrtlFlux.h
  sbncode/EventGenerator/MeVPrtl/config/numi_kaon_common.fcl
  sbncode/LArRecoProducer/transfer_flashmatch_producer.fcl
  sbncode/TPCReco/VertexStub/config/sbn_stub.fcl
Labels: help wanted

#120 Feature/etyley caf units
  sbncode/CAFMaker/FillReco.cxx
Labels: documentation
