Repository SBNSoftware/sbncode, pull requests merged in 2021-11, with the labels that each got.

#184 Make End Median dQ/dx range configurable. Move range to 2cm in ICARUS.
  sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc
  sbncode/Calibration/fcl/icarus/icarus_trackcalo_skimmer.fcl
  sbncode/Calibration/fcl/sbnd/sbnd_trackcalo_skimmer.fcl
Labels: enhancement

#178 Updates to Calibration Workflows
  sbncode/Calibration/TrackCaloSkimmer.h
  sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc
  sbncode/Calibration/TrackCaloSkimmer_module.cc
  sbncode/Calibration/notebook/ExtractDriftVelocity.ipynb
  sbncode/Calibration/notebook/ExtractElectronLifetime.ipynb
  sbncode/Calibration/notebook/StoppingdEdx.ipynb
  sbncode/Calibration/notebook/StoppingdQdx.ipynb
  sbncode/Calibration/notebook/lib/__init__.py
  sbncode/Calibration/notebook/lib/branches.py
  sbncode/Calibration/notebook/lib/constants.py
  sbncode/Calibration/notebook/lib/dedx.py
  sbncode/Calibration/notebook/lib/glob.py
  sbncode/Calibration/notebook/lib/names.py
  sbncode/Calibration/notebook/lib/plot.py
  sbncode/Calibration/notebook/make_calib_df.py
  sbncode/Calibration/notebook/make_driftV_df.py
  sbncode/Calibration/notebook/make_equalibriate_df.py
  sbncode/Calibration/notebook/make_etau_df.py
  sbncode/Calibration/notebook/requirements.txt
  sbncode/TPCReco/TrackHit/TrackAreaHit_module.cc
Labels: enhancement

#195 port T. Brooks' GeometryWrappers over from sbndcode so they can be us…
  sbncode/CMakeLists.txt
  sbncode/GeometryTools/CMakeLists.txt
  sbncode/GeometryTools/CRTGeoAlg.cc
  sbncode/GeometryTools/CRTGeoAlg.h
  sbncode/GeometryTools/TPCGeoAlg.cc
  sbncode/GeometryTools/TPCGeoAlg.h
Labels: test

#193 Update ICARUS detector location and detector box
  sbncode/EventGenerator/MeVPrtl/config/numi_kaon_common.fcl
Labels: maintenance

#197 Feature/jlarkin refactor cafmaker fcl
  fcl/caf/CMakeLists.txt
  fcl/caf/cafmaker_common_defs.fcl
  fcl/caf/sbnd/CMakeLists.txt
  fcl/caf/sbnd/cafmakerjob_sbnd.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_3drift_sce.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_3drift_sce_runfmatch.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_3drift_sce_runfmatch_geniewgt.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_fmatch.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_geniewgt.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_sce.fcl
  fcl/caf/sbnd/cafmakerjob_sbnd_sce_genie_and_fluxwgt.fcl
Labels: maintenance

#199 This is a fix for a seg-fault arising from missing MWR devices
  sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
Labels: bug

#192 Update SBNEventWeight Module FHiCLs.
  CMakeLists.txt
  fcl/caf/cafmaker_common_defs.fcl
  sbncode/SBNEventWeight/Calculators/BNBFlux/FluxCalcPrep.cxx
  sbncode/SBNEventWeight/jobs/flux/eventweight_flux_sbn.fcl
  sbncode/SBNEventWeight/jobs/genie/eventweight_genie3_sbn_A.fcl
  sbncode/SBNEventWeight/jobs/genie/eventweight_genie_sbn.fcl
  sbncode/SBNEventWeight/jobs/run_eventweight_sbn.fcl
  ups/product_deps
Labels: bug

#196 Calibration NTuple Update
  sbncode/Calibration/TrackCaloSkimmer.h
  sbncode/Calibration/TrackCaloSkimmer_module.cc
Labels: maintenance
