Repository SBNSoftware/sbncode, pull requests merged in 2021-07, with the labels that each got.

#134 Remove GENIE v2 flag
  fcl/gen/genie/prodgenie_bnb_nu_cosmic_sbn_icarus.fcl
  fcl/gen/genie/prodgenie_bnb_nu_cosmic_sbn_sbnd.fcl
  fcl/gen/genie/prodgenie_bnb_nu_cosmic_sbn_uboone.fcl
  fcl/gen/genie/prodgenie_bnb_nu_sbn_icarus.fcl
  fcl/gen/genie/prodgenie_bnb_nu_sbn_sbnd.fcl
  fcl/gen/genie/prodgenie_bnb_nu_sbn_uboone.fcl
Labels: invalid

#130 FluxReader Addition
  sbncode/CMakeLists.txt
  sbncode/FluxReader/CMakeLists.txt
  sbncode/FluxReader/DK2NuInterface.cxx
  sbncode/FluxReader/DK2NuInterface.h
  sbncode/FluxReader/FluxGeoFilter_module.cc
  sbncode/FluxReader/FluxInterface.h
  sbncode/FluxReader/FluxReader.cxx
  sbncode/FluxReader/FluxReader.h
  sbncode/FluxReader/FluxReader_source.cc
  sbncode/FluxReader/GSimpleInterface.cxx
  sbncode/FluxReader/GSimpleInterface.h
  sbncode/FluxReader/classes.h
  sbncode/FluxReader/classes_def.xml
  sbncode/FluxReader/job/CMakeLists.txt
  sbncode/FluxReader/job/fluxfilter_sbnd.fcl
  sbncode/FluxReader/job/legacy/fluxreader_evwgh.fcl
  sbncode/FluxReader/job/legacy/fluxreader_source.fcl
  sbncode/FluxReader/job/legacy/fluxreader_source_dk2nu.fcl
  sbncode/FluxReader/job/run_fluxreader_incr_run_sbnd.fcl
  sbncode/FluxReader/job/run_fluxreader_sbnd.fcl
Labels: enhancement

#135 FluxReader
  sbncode/FluxReader/FluxReader.h
Labels: bug

#115 Updates to Stub Reconstruction
  sbncode/TPCReco/CMakeLists.txt
  sbncode/TPCReco/NuVertexChargeTree_module.cc
  sbncode/TPCReco/VertexStub/CMakeLists.txt
  sbncode/TPCReco/VertexStub/IStubMerge.h
  sbncode/TPCReco/VertexStub/PlaneStubMerge_tool.cc
  sbncode/TPCReco/VertexStub/PlaneTransform.cxx
  sbncode/TPCReco/VertexStub/PlaneTransform.h
  sbncode/TPCReco/VertexStub/StubBuilder.cxx
  sbncode/TPCReco/VertexStub/StubBuilder.h
  sbncode/TPCReco/VertexStub/StubMergeAlgorithms.cxx
  sbncode/TPCReco/VertexStub/StubMergeAlgorithms.h
  sbncode/TPCReco/VertexStub/TwoPlaneStubMerge_tool.cc
  sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
  sbncode/TPCReco/VertexStub/VertexStubTracker_module.cc
  sbncode/TPCReco/VertexStub/sbn_plane_transform.fcl
  sbncode/TPCReco/VertexStub/sbn_stub_merge_tools.fcl
  sbncode/TPCReco/run_vertexcharge_sbnd.fcl
Labels: enhancement

#132 Razzle Dazzle PID
  sbncode/CAFMaker/CAFMakerParams.h
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/FillReco.cxx
  sbncode/CAFMaker/FillReco.h
  sbncode/CAFMaker/cafmakerjob_icarus.fcl
  sbncode/CAFMaker/cafmakerjob_icarus_sce.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_3drift_sce_runfmatch.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_3drift_sce_runfmatch_geniewgt.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_fmatch.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_geniewgt.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_sce.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_sce_geniewgt.fcl
  sbncode/CMakeLists.txt
  sbncode/LArRecoProducer/LArReco/CMakeLists.txt
  sbncode/LArRecoProducer/ShowerCosmicDistance_module.cc
  sbncode/LArRecoProducer/TrackScatterClosestApproach_module.cc
  sbncode/LArRecoProducer/TrackStoppingChi2Fitter_module.cc
  sbncode/LArRecoProducer/TransferPFParticleFlashMatch_module.cc
  sbncode/LArRecoProducer/showercosmicdistanceproducer.fcl
  sbncode/LArRecoProducer/showerselectionvarsproducer.fcl
  sbncode/LArRecoProducer/trackscatterclosestapproach.fcl
  sbncode/LArRecoProducer/trackstoppingchi2fitter.fcl
  sbncode/LArRecoProducer/transfer_flashmatch_producer.fcl
  sbncode/PID/CMakeLists.txt
  sbncode/PID/Dazzle_module.cc
  sbncode/PID/README.md
  sbncode/PID/Razzle_module.cc
  sbncode/PID/sbn_pid.fcl
  sbncode/PID/scripts/ShowerPIDMVA.C
  sbncode/PID/scripts/TrackPIDMVA.C
Labels: enhancement

#136 Update razzle-dazzle Weights
  sbncode/PID/sbn_pid.fcl
Labels: maintenance

#140 Porting MultiPart event generator from icaruscode to sbncode
  sbncode/EventGenerator/CMakeLists.txt
  sbncode/EventGenerator/MultiPart/CMakeLists.txt
  sbncode/EventGenerator/MultiPart/MultiPartRain_module.cc
  sbncode/EventGenerator/MultiPart/MultiPartVertex_module.cc
  sbncode/EventGenerator/MultiPart/multipartvertex_icarus.fcl
  sbncode/EventGenerator/MultiPart/multipartvertex_sbnd.fcl
Labels: maintenance

#144 Avoid crashing when there are no valid weights if StrictMode=false
  sbncode/CAFMaker/CAFMaker_module.cc
Labels: bug

#147 Update Calorimetry in CAFMaker
  sbncode/CAFMaker/CAFMakerParams.h
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/CMakeLists.txt
  sbncode/CAFMaker/FillReco.cxx
  sbncode/CAFMaker/FillReco.h
  sbncode/CAFMaker/cafmakerjob_icarus.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd.fcl
Labels: enhancement

#126 Update metadata services.
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/Metadata/CMakeLists.txt
  sbncode/Metadata/FileCatalogMetadataSBN.h
  sbncode/Metadata/FileCatalogMetadataSBN_service.cc
  sbncode/Metadata/MetadataSBN.h
  sbncode/Metadata/MetadataSBN_service.cc
Labels: enhancement

#149 Updates to Track Skimming. Add in end-point-hit information and truth information
  sbncode/CAFMaker/FillTrue.cxx
  sbncode/CAFMaker/FillTrue.h
  sbncode/Calibration/CMakeLists.txt
  sbncode/Calibration/TrackCaloSkimmer.h
  sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc
  sbncode/Calibration/TrackCaloSkimmer_module.cc
  sbncode/Calibration/fcl/icarus_trackcalo_skimmer.fcl
Labels: enhancement

#141 Refactor configs and products out of sbncode for MeVPrtl Event Generator
  sbncode/EventGenerator/MeVPrtl/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/MeVPrtlGen_module.cc
  sbncode/EventGenerator/MeVPrtl/MeVPrtlTestRayTrace_module.cc
  sbncode/EventGenerator/MeVPrtl/Products/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/Products/KaonParent.cxx
  sbncode/EventGenerator/MeVPrtl/Products/KaonParent.h
  sbncode/EventGenerator/MeVPrtl/Products/LinkDef.h
  sbncode/EventGenerator/MeVPrtl/Products/MeVPrtlDecay.h
  sbncode/EventGenerator/MeVPrtl/Products/MeVPrtlFlux.h
  sbncode/EventGenerator/MeVPrtl/Products/MeVPrtlTruth.cxx
  sbncode/EventGenerator/MeVPrtl/Products/MeVPrtlTruth.h
  sbncode/EventGenerator/MeVPrtl/Products/classes.h
  sbncode/EventGenerator/MeVPrtl/Products/classes_def.xml
  sbncode/EventGenerator/MeVPrtl/Tools/EmptyKaonGen_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/HNLMakeDecay_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/Kaon2HNLFlux_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/Higgs/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/Tools/Higgs/HiggsMakeDecay_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/Higgs/Kaon2HiggsFlux_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/Higgs/MonoEnergyHiggsFlux_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/IMeVPrtlDecay.h
  sbncode/EventGenerator/MeVPrtl/Tools/IMeVPrtlFlux.h
  sbncode/EventGenerator/MeVPrtl/Tools/IRayTrace.h
  sbncode/EventGenerator/MeVPrtl/Tools/MixedWeightRayTraceBox_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/RayTraceBox_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/ReThrowRayTraceBox_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/WeightedRayTraceBox_tool.cc
  sbncode/EventGenerator/MeVPrtl/config/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/config/HNL/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/config/HNL/hnl.fcl
  sbncode/EventGenerator/MeVPrtl/config/HNL/set_hnlM.fcl
  sbncode/EventGenerator/MeVPrtl/config/Higgs/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/config/Higgs/dissonant_higgs.fcl
  sbncode/EventGenerator/MeVPrtl/config/Higgs/set_higgsM.fcl
  sbncode/EventGenerator/MeVPrtl/config/numi_kaon_common.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M260.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M280.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M300.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M320.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M340.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M360.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_M380.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_icarus_gen.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_testray_icarus.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/HNL/hnl_tree_icarus.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/dissH_M220.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/dissH_M260.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/dissH_M300.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/dissH_M340.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/dissonant_higgs_gen.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/Higgs/dissonant_higgs_tree_icarus.fcl
  sbncode/EventGenerator/MeVPrtl/jobs/icarus_nu_bkg.fcl
Labels: maintenance

#143 Stubs in ICARUS and with Space Charge
  sbncode/TPCReco/NuVertexChargeTree_module.cc
  sbncode/TPCReco/VertexStub/CMakeLists.txt
  sbncode/TPCReco/VertexStub/PlaneTransform.cxx
  sbncode/TPCReco/VertexStub/PlaneTransform.h
  sbncode/TPCReco/VertexStub/StubBuilder.cxx
  sbncode/TPCReco/VertexStub/StubBuilder.h
  sbncode/TPCReco/VertexStub/StubMergeAlgorithms.cxx
  sbncode/TPCReco/VertexStub/StubMergeAlgorithms.h
  sbncode/TPCReco/VertexStub/TwoPlaneStubMerge_tool.cc
  sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
  sbncode/TPCReco/VertexStub/VertexStubTracker_module.cc
  sbncode/TPCReco/VertexStub/sbn_plane_transform.fcl
  sbncode/TPCReco/VertexStub/sbn_stub_merge_tools.fcl
  sbncode/TPCReco/run_vertexcharge_sbnd.fcl
Labels: maintenance

#145 Stubs in CAFMaker
  sbncode/CAFMaker/CAFMakerParams.h
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/FillReco.cxx
  sbncode/CAFMaker/FillReco.h
  sbncode/CAFMaker/FillTrue.cxx
  sbncode/CAFMaker/FillTrue.h
  sbncode/CAFMaker/cafmakerjob_sbnd.fcl
  sbncode/CAFMaker/cafmakerjob_sbnd_sce.fcl
  sbncode/TPCReco/VertexStub/CMakeLists.txt
  sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
  sbncode/TPCReco/VertexStub/config/CMakeLists.txt
  sbncode/TPCReco/VertexStub/config/sbn_stub.fcl
  sbncode/TPCReco/VertexStub/config/sbn_stub_merge_tools.fcl
Labels: enhancement

#146 Fill Objects for MeVPrtl in StandardRecord
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/FillTrue.cxx
  sbncode/CAFMaker/FillTrue.h
Labels: enhancement
