Repository SBNSoftware/sbncode, pull requests merged in 2022-05, with the labels that each got.

#263 add headers needed by larsoft v09_50_00
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/RecoUtils/RecoUtils.h
  sbncode/Calibration/TrackCaloSkimmer.h
  sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc
  sbncode/EventGenerator/MultiPart/MultiPartRain_module.cc
  sbncode/EventGenerator/MultiPart/MultiPartVertex_module.cc
  sbncode/FluxReader/FluxGeoFilter_module.cc
  sbncode/FluxReader/FluxReader.cxx
  sbncode/GeometryTools/CRTGeoAlg.h
  sbncode/GeometryTools/TPCGeoAlg.h
  sbncode/NuMuSelection/MuPVertexStudy_module.cc
  sbncode/NuMuSelection/MuonS2NStudy_module.cc
  sbncode/NuMuSelection/NuMuEfficiencyStudy_module.cc
  sbncode/PID/Razzle_module.cc
  sbncode/TPCReco/CalorimetryAnalysis/CalorimetryAnalysis_module.cc
  sbncode/TPCReco/NuVertexChargeTree_module.cc
  sbncode/TPCReco/TrackHit/TrackAreaHit_module.cc
  sbncode/TPCReco/TrackSplit/MergedTrackIdentifier_module.cc
  sbncode/TPCReco/TrackSplit/TrackSplitter_module.cc
  sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
  sbncode/TPCReco/VertexStub/VertexStubTracker_module.cc
Labels: maintenance

#267 Fix accidental overwrite in FluxReader
  sbncode/FluxReader/FluxReaderAna_module.cc
Labels: bug

#266 Add example training script for CRUMBS tool
  sbncode/CosmicID/training_scripts/CRUMBSTMVADriver.C
Labels: documentation

#268 Updates to POT accounting codes to account for new trigger fragment
  sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
  sbncode/BeamSpillInfoRetriever/NuMIRetriever/NuMIRetriever_module.cc
Labels: bug

#269 Updates to POT accounting codes to account for new trigger fragment. …
  sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
  sbncode/BeamSpillInfoRetriever/NuMIRetriever/NuMIRetriever_module.cc
Labels: bug
