Repository SBNSoftware/sbncode, pull requests merged in 2025-02, with the labels that each got.

#490 Updating to better handle the making of space points with one of thre…
  sbncode/Cluster3D/SnippetHit3DBuilderSBN_tool.cc
  sbncode/Cluster3D/cluster3dalgorithms_sbn.fcl
Labels: bug, bugfix

#492 Added SBN (shared) GENIE configuration for BNB and NuMI
  fcl/gen/genie/genie_beam_settings.fcl
Labels: enhancement

#493 Save CVN scores in CAFMaker.
  sbncode/CAFMaker/CAFMakerParams.h
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/CMakeLists.txt
  sbncode/CAFMaker/FillReco.cxx
  sbncode/CAFMaker/FillReco.h
Labels: enhancement

#503 Flatten the GENIE event record in flat CAF
  sbncode/CAFMaker/CAFMaker_module.cc
Labels: refactor

#501 Fix bugs in v10 upgrade.
  sbncode/CAFMaker/FillTrue.cxx
  sbncode/Cluster3D/SnippetHit3DBuilderSBN_tool.cc
  sbncode/TPCReco/NuVertexChargeTree_module.cc
  sbncode/TPCReco/VertexStub/StubBuilder.cxx
  sbncode/TPCReco/VertexStub/StubMergeAlgorithms.cxx
  sbncode/TPCReco/VertexStub/StubMergeAlgorithms.h
  sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
Labels: bugfix

#502 Lepton Meson HNL Anisotropies and HNL Polarization fix
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/AnisotropicThreeBodyDecay.cpp
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/AnisotropicThreeBodyDecay.h
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/AnisotropicTwoBodyDecay.cpp
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/AnisotropicTwoBodyDecay.h
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/CMakeLists.txt
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/HNLMakeDecay_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/Kaon2HNLFlux_tool.cc
  sbncode/EventGenerator/MeVPrtl/Tools/HNL/Tau2HNLFlux_tool.cc
  sbncode/EventGenerator/MeVPrtl/config/HNL/hnl.fcl
Labels: enhancement

#509 Add RadioactiveDecayBase to CAFMaker
  sbncode/CAFMaker/FillTrue.cxx
Labels: bug
