Repository SBNSoftware/sbncode, pull requests merged in 2025-04, with the labels that each got.

#525 Fix Handling of CRT in Calbiration NTupler
  sbncode/Calibration/TrackCaloSkimmer.h
  sbncode/Calibration/TrackCaloSkimmer_module.cc
  sbncode/Calibration/fcl/icarus/icarus_trackcalo_skimmer.fcl
  sbncode/Calibration/fcl/sbnd/sbnd_trackcalo_skimmer.fcl
Labels: bugfix

#527 Use Ts0 not Ts1
  sbncode/CAFMaker/FillReco.cxx
Labels: maintenance

#533 Modify `MergeSimChannels` signature with check to skip G4 tracks or not
  sbncode/LArG4/MergeSimSourcesSBN_module.cc
  ups/product_deps
Labels: bugfix

#535 Feature/usher channel roi update
  sbncode/CMakeLists.txt
  sbncode/HitFinder/CMakeLists.txt
  sbncode/HitFinder/ChannelROIToWire_module.cc
  sbncode/HitFinder/GaussHitFinderSBN_module.cc
  sbncode/HitFinder/HitFinderUtilities/CMakeLists.txt
  sbncode/HitFinder/HitFinderUtilities/HitCreator.cxx
  sbncode/HitFinder/HitFinderUtilities/HitCreator.h
  sbncode/HitFinder/WireToChannelROI_module.cc
  sbncode/HitFinder/hitfindermodules_sbn.fcl
  sbncode/HitFinder/wirechannelroiconverters_sbn.fcl
Labels: enhancement

#534 Save OpFlash information in CAF files in SBND.
  sbncode/CAFMaker/CAFMaker_module.cc
  sbncode/CAFMaker/FillReco.cxx
  sbncode/CAFMaker/FillReco.h
Labels: enhancement
